### ISSUE TITLE
How to fix AttributeError: 'Web3' object has no attribute 'toChecksumAddress

### ISSUE THREAD

**Issue by active2323** [JozefJarosciak/xenft-creator#1]
How do I fix:

Traceback (most recent call last):
  File "C:\Users\joegs\Desktop\xenft-creator.py", line 57, in <module>
    xenft_contract_address = web3.toChecksumAddress('0x0a252663dbcc0b073063d6420a40319e438cfa59')
AttributeError: 'Web3' object has no attribute 'toChecksumAddress'

**Comment by cdenario** [comment]
same issue

**Comment by JozefJarosciak** [comment]
are you using web3~=5.31.1?
